apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: circuit-breaker-service-middleware-java
  namespace: on-premise
  labels:
    type: circuit-breaker
spec:
  host: service-middleware-java.on-premise.svc.cluster.local
  trafficPolicy:
    outlierDetection:
        baseEjectionTime: 30s
        consecutiveErrors: 2
        interval: 10s
        maxEjectionPercent: 100