apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: on-premise
  name: mongo-db
  labels:
    type: data-base
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template: 
    metadata:
      labels:
        app: db
        type: data-base
    spec:
      containers:
      - name: db
        image: mongo:3.4
---
apiVersion: v1
kind: Service
metadata:
  namespace: on-premise
  name: service-db
  labels:
    type: data-base
spec:
  selector:
    app: db
  ports:
    - name: http
      port: 27017
  type: ClusterIP
