apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: on-premise
  name: api-rest
  labels:
    type: back-end
spec:
  selector:
    matchLabels:
      app: api-rest
  replicas: 1
  template: 
    metadata:
      labels:
        app: api-rest
        type: back-end
    spec:
      containers:
      - name: api-rest
        image: leviditomazzo/api-financial:v2
        env:
        - name: DB_HOST
          value: 'service-db:27017'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: on-premise
  name: api-rest-java
  labels:
    type: back-end
spec:
  selector:
    matchLabels:
      app: api-rest-java
  replicas: 1
  template: 
    metadata:
      labels:
        app: api-rest-java
        type: back-end
    spec:
      containers:
      - name: api-rest-java
        image: leviditomazzo/api-rest-java:v1
---
apiVersion: v1
kind: Service
metadata:
  namespace: on-premise
  name: service-api-rest
  labels:
    type: back-end
spec:
  selector:
    app: api-rest
  ports:
    - name: http
      port: 4011
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  namespace: on-premise
  name: service-api-rest-java
  labels:
    type: back-end
spec:
  selector:
    app: api-rest-java
  ports:
    - name: http
      port: 8080
      nodePort: 30070
  type: NodePort
