apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: on-premise
  name: api-simulation
  labels:
    type: back-end
spec:
  selector:
    matchLabels:
      app: api-simulation
  replicas: 1
  template: 
    metadata:
      labels:
        app: api-simulation
        type: back-end
        version: iof
    spec:
      containers:
      - name: api-simulation
        image: leviditomazzo/api-simulation:iof
        env:
        - name: PORT
          value: '8084'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: on-premise
  name: api-rest
  labels:
    type: back-end
spec:
  selector:
    matchLabels:
      app: api-rest
  replicas: 1
  template: 
    metadata:
      labels:
        app: api-rest
        type: back-end
    spec:
      containers:
      - name: api-rest
        image: leviditomazzo/api-financial:v2
        env:
        - name: DB_HOST
          value: 'service-db:27017'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: on-premise-2
  name: api-rest-java
  labels:
    type: back-end
spec:
  selector:
    matchLabels:
      app: api-rest-java
  replicas: 1
  template: 
    metadata:
      labels:
        app: api-rest-java
        type: back-end
    spec:
      containers:
      - name: api-rest-java
        image: leviditomazzo/api-rest-java:v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: on-premise
  name: middleware-java
  labels:
    type: middleware
spec:
  selector:
    matchLabels:
      app: middleware-java
  replicas: 1
  template: 
    metadata:
      labels:
        app:  middleware-java
        type: middleware
    spec:
      containers:
      - name: middleware
        image: fandrade/chamador-api
        env:
        - name: URL_SERVICO
          value: 'http://service-api-rest-java.on-premise-2.svc.cluster.local:8080/retornaDados'
---
apiVersion: v1
kind: Service
metadata:
  namespace: on-premise
  name: service-api-simulation
  labels:
    type: back-end
spec:
  selector:
    app: api-simulation
  ports:
    - name: http
      port: 8084
      nodePort: 30074
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  namespace: on-premise
  name: service-api-rest
  labels:
    type: back-end
spec:
  selector:
    app: api-rest
  ports:
    - name: http
      port: 4011
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  namespace: on-premise-2
  name: service-api-rest-java
  labels:
    type: back-end
spec:
  selector:
    app: api-rest-java
  ports:
    - name: http
      port: 8080
      nodePort: 30070
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  namespace: on-premise
  name: service-middleware-java
  labels:
    type: middleware
spec:
  selector:
    app: middleware-java
  ports:
    - name: http
      port: 9003
      nodePort: 30076
  type: NodePort
