apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: on-premise
  name: web-app
  labels:
    type: front-end
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 1
  template: 
    metadata:
      labels:
        app: web-app
        type: front-end
        version: production
    spec:
      containers:
      - name: web-app
        image: leviditomazzo/front-end:auth0v2
        env:
        - name: REACT_APP_API_GRAPHQL_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map-graphql
              key: END_POINT_API_GRAPHQL

        - name: REACT_APP_DOMAIN
          value: leviditomazzo.auth0.com
    
        - name: REACT_APP_CLIENT_ID
          value: b1oE7t6uLIYpBv0OYSD28VJTCFTvYxcN

        - name: REACT_APP_AUDIENCE
          value: https://levi-api-auth0
---
apiVersion: v1
kind: Service
metadata:
  namespace: on-premise
  name: service-web-app
  labels:
    type: front-end
spec:
  selector:
    app: web-app
  ports:
    - name: http
      port: 3000
  type: ClusterIP
