apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: timeout-virtual-service-api-java
  namespace: on-premise
spec:
  hosts:
    - service-middleware-java
  http:
  - route:
    - destination:
        host: service-middleware-java
    timeout: 2s
    retries:
      attempts: 3
      perTryTimeout: 2s
        
