apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: timeout-virtual-service-api-java
  namespace: on-premise
spec:
  hosts:
  - service-middleware-java.on-premise.svc.cluster.local
  http:
    - route:
      - destination:
          host: service-middleware-java.on-premise.svc.cluster.local
      timeout: 0.2s
      retries:
        attempts: 1
        perTryTimeout: 1s