apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-api-java
  namespace: on-premise
spec:
  hosts:
    - service-middleware-java.on-premise.svc.cluster.local
  http:
    - fault:
        delay:
          fixedDelay: 5s
          percentage:
            value: 100
      route:
        - destination:
            host: service-middleware-java.on-premise.svc.cluster.local
