apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-api-java
  namespace: on-premise
  labels:
    kiali_wizard: suspend_traffic
spec:
  hosts:
    - service-middleware-java.on-premise.svc.cluster.local
  http:
    - fault:
        abort:
          httpStatus: 503
          percentage:
            value: 100
      route:
        - destination:
            host: service-middleware-java.on-premise.svc.cluster.local